name: contas
version: "3.8"

services:
  contas_app:
    image: angelomoreirafilho/gestao-contas:${IMAGE_TAG:-0.1.7}
    
    networks:
      - BrancaNet

    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - APP_URL=${APP_URL}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    volumes:
      - contas_data:/app/data

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          memory: 128M

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.contas_app.rule=Host(`contas.brancaautoescola.com.br`)"
        - "traefik.http.routers.contas_app.entrypoints=websecure"
        - "traefik.http.routers.contas_app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.contas_app.loadbalancer.server.port=3000"
        - "traefik.docker.network=BrancaNet"

networks:
  BrancaNet:
    external: true

volumes:
  contas_data:
    name: contas_data
